1. Cread tres arrays: de una, dos y tres dimensiones.

Lo podéis hacer usando los métodos de random que hemos aprendido o a través de listas en algunos casos.

📌 Nota:
- El array de 2 dimensiones debe ser de 2 filas y 3 columnas
- El array de 3 dimensiones debe ser de 2 matrices, 3 filas y 5 columnas

In [1]:
# Importamos la librería
import numpy as np 

In [2]:
# Array de 1 dimensión
array1 = np.random.randint(1,100,(2))
array1

array([ 5, 62])

In [3]:
# Array de 2 dimensiones (2 filas y 3 columnas)
array2 = np.random.randint(1,100,(2,3))
array2 

array([[ 4, 81, 53],
       [88, 39, 78]])

In [4]:
# Array de 3 dimensiones (2 matrices, 3 filas y 5 columnas)
array3 = np.random.randint(1,100,(2,3,5))
array3 

array([[[37, 50, 76, 81, 19],
        [29, 38, 53, 49, 64],
        [26, 47, 49,  9, 80]],

       [[59, 42, 45, 85, 35],
        [54, 99, 97, 49, 82],
        [50, 13, 20, 90, 54]]])

2. Chequed las las propiedades básicas de cada array que os hayáis creado. Usad en una función que nos devuelva las propiedades de una array que le pasemos.

In [5]:
def propiedades(array): # Definimos la función de propiedades que toma como parametro el array y printea las propiedades de forma, tamaño, dimensión y tipo
    print(f'La forma es {array.shape}')
    print(f'El tamaño es {array.size}')
    print(f'La dimensión es {array.ndim}')
    print(f'El tipo es {array.dtype}')


In [6]:
def propiedades2(array):# Otra forma de hacerlo con un return de todas las propiedades seguidas
    return f"La forma es {array.shape}, el tamaño es {array.size}, la dimensión es {array.ndim} y el tipo es {array.dtype}"


In [7]:
propiedades2(array1)

'La forma es (2,), el tamaño es 2, la dimensión es 1 y el tipo es int64'

In [8]:
propiedades(array2)

La forma es (2, 3)
El tamaño es 6
La dimensión es 2
El tipo es int64


In [9]:
propiedades2(array3)

'La forma es (2, 3, 5), el tamaño es 30, la dimensión es 3 y el tipo es int64'

3. Cread una matriz identidad de dos dimensiones de 3 filas y 3 columnas

In [10]:
# Creaamos la matriz con el con método identity
matriz_identidad1 = np.identity(3) 
matriz_identidad1

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

4.Cread una matriz de tres dimensiones de unos igual a la martiz de tres dimensiones creada en el primer ejercicio.

In [11]:
# Creamos el array con método ones_like e indicamos en nombre de la matriz array3, que es de la que queremos copiar.
array4 = np.ones_like(array3) 
array4

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

5. Es el momento de hacer algunas operaciones entre arrays

¿Se puede sumar el array de dos dimensiones que creamos en el primer ejecicios a la matriz identidad? 
¿Por qué?

En caso de que no se puedan sumar, busca una solución para sumar una matriz identidad a otra. La solución puede ser crear un array nuevo.

Multiplicad la matriz identidad por la nueva matriz que os creasteis en el ejercicio anterior.

Dividid las dos matricess

In [12]:
#No se pueden sumar arrays de diferente forma 
np.add(array2,matriz_identidad1)

ValueError: operands could not be broadcast together with shapes (2,3) (3,3) 

In [13]:
# Creamos una matriz de unos de la misma forma que la matriz identidad
array5 = np.ones_like(matriz_identidad1)
array5

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [14]:
# Sumamos con método add
np.add(array5,matriz_identidad1)

array([[2., 1., 1.],
       [1., 2., 1.],
       [1., 1., 2.]])

In [15]:
# Multiplicamos 
np.multiply(array5,matriz_identidad1)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
# Dividimos 
np.divide(matriz_identidad1,array5,)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])