In [1]:
import numpy as np

1- ¿Cómo podemos crear dos arrays de dos dimensiones usando el método random_sample que tengan los mismos valores?

In [2]:
# Utilizando random.seed podemos crear dos arrays con los mismos valores
np.random.seed(1)
arr1=np.random.rand(5,2)
arr1

array([[4.17022005e-01, 7.20324493e-01],
       [1.14374817e-04, 3.02332573e-01],
       [1.46755891e-01, 9.23385948e-02],
       [1.86260211e-01, 3.45560727e-01],
       [3.96767474e-01, 5.38816734e-01]])

In [3]:
np.random.seed(1)
arr2=np.random.rand(5,2)
arr2

array([[4.17022005e-01, 7.20324493e-01],
       [1.14374817e-04, 3.02332573e-01],
       [1.46755891e-01, 9.23385948e-02],
       [1.86260211e-01, 3.45560727e-01],
       [3.96767474e-01, 5.38816734e-01]])

2- Cread los siguientes arrays:
- Un array de tres dimensiones con distribución uniforme de 2 x 3 x 5, con números entre 0 y 10, que no tengan decimales y extrae sus valores únicos almacenándolos en una variable.
- Un array de tres dimensiones con distribución binomial de 2 x 3 x 5, con probabilidad de 0.3 y número de pruebas igual a 10. Igual que antes, extrae sus valores únicos y guarda los datos en una variable.

In [4]:
# Creamos res dimensiones con distribución uniforme de 2 x 3 x 5 con numeros del 0 al 10 de enteros con el método astype
array_1 = np.random.uniform(size=(2,3,5), low = 0, high =10).astype(int)
print (array_1)
print ('-----------------------------------')
array_1_unique = np.unique(array_1) #Extraemos los valores únicos con np.unique
print(array_1_unique)

[[[4 6 2 8 0]
  [6 4 5 1 1]
  [8 9 3 6 8]]

 [[8 0 0 1 8]
  [0 4 9 5 6]
  [3 6 8 0 7]]]
-----------------------------------
[0 1 2 3 4 5 6 7 8 9]


In [5]:
# Creamos res dimensiones con distribución binomial de 2 x 3 x 5 con probabilidad de 0.3 y 10 pruebas
array_2 = np.random.binomial(10, 0.3, size=(2,3,5))
print (array_2)
print ('-----------------------------------')
array_2_unique = np.unique(array_2) #Extraemos los valores únicos con np.unique
print(array_2_unique)

[[[6 4 2 4 1]
  [3 5 2 2 1]
  [0 4 2 2 3]]

 [[1 3 1 3 4]
  [1 3 4 3 1]
  [3 4 3 5 3]]]
-----------------------------------
[0 1 2 3 4 5 6]


3- En esta lección hemos aprendido algunos métodos de teórias de conjuntos. Usando los arrays de elementos únicos obtenidos en el ejercicio anterior realizad las siguientes operaciones:
- Elementos comunes entre los dos arrays
- Unión de los dos arrays
- ¿Qué elementos están en el array derivado de la distribución uniforme y no en los únicos de la distribución binomial? Extrae los valores númericos

⚠️ Explicar cada uno de los outputs que os salgan. Que significa cada una de estas operaciones que hemos ido extrayendo?


In [6]:
#Elementos comunes:
np.intersect1d(array_1,array_2)
# Los elementos que están en ambos arrays los extraemos con intersect1d, estos números están en ambos arrays y lo devuelve como un array ordenado y en valores únicos.
# Como en array1 tenemos todos los números del 0 al 9 y en el array2 del 0 al 5, los elementos comunes son del 0 al 6.


array([0, 1, 2, 3, 4, 5, 6])

In [7]:
#Unión de los dos arrays
np.union1d(array_1,array_2)
#Devuelve un array ordenado con valores únicos de los tomando los números que están tanto en un array como en otro.
#Al unir ambos arrays, como los valores del array2 están contenidos en el array1 la unión de ambos son los números unicos del array1.

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
#Elementos están en el array derivado de la distribución uniforme y no en los únicos de la distribución binomial
np.setdiff1d(array_1,array_2_unique)
# Devuelve los elementos que se encuentran en el array1 y no se encuentran en los únicos del array2
# La diferencia entra ambos son los números que no están en el array2, es decir del 7 al 9.

array([7, 8, 9])

4- Cread dos arrays usando el método random.randint de Numpy con 80 elementos cada uno con números del 1-100, con los siguientes nombres array1 y array2. 
- Extraed los valores únicos de cada uno de los arrays y los guardáis en variables en las que se les llame array1 y array2.
- Identificad los elementos presentes en el array1 pero no en el array2 y asiganarlo a una variable que se llame array3.
- Identificad los elementos presentes en el array2 pero no en el array1 y asiganarlo a una variable que se llame array4.
- Identificad los elementos presentes en ambos arrays y asiganarlos a una variable que se llame array5.
- ¿Cuál es la relación que existe entre todos estos arrays? 💡 Pista 💡 Tendréis que usar las longitudes de cada uno de los arrays creados.

In [9]:
array1 = np.random.randint(1,100,(80))
print(array1)
print ('-------------------------------')
array2 = np.random.randint(1,100,(80))
print(array2)

[ 8 78 73 76 77 44 21 31 37  8 46 69 58 83 97 14 11 24 82  8 25 75 93 21
 33 13 66 95 61 25 83 98  3 93 99 11 55 97 83 87 71 67 72 49 55 16  6 18
 43 21 49 23 14 98 54 85 11 97 56 62 57 90 22 97 84 26 15 14 85 44  7 78
 57 60 16 25 10 67 72 54]
-------------------------------
[70 37 22 41 78 92 50 48 78 41 79 46 88 17 29 46 68 67 79 47  1 30 64 76
 36 54 94 34  3 85 84 49 55 33 29 56 83 32 29 95 75  9 33  9 85 78 51 80
 42 65 84 25 21 45 16 31 92 15 20 27 87  8 54 48 61 35 33 20 68 25 84 95
 39 48  6 80 64 88 33 43]


In [10]:
#Valores únicos
array1= np.unique(array1)
print(array1)
print ('-------------------------------')
array2= np.unique(array2)
print(array2)

[ 3  6  7  8 10 11 13 14 15 16 18 21 22 23 24 25 26 31 33 37 43 44 46 49
 54 55 56 57 58 60 61 62 66 67 69 71 72 73 75 76 77 78 82 83 84 85 87 90
 93 95 97 98 99]
-------------------------------
[ 1  3  6  8  9 15 16 17 20 21 22 25 27 29 30 31 32 33 34 35 36 37 39 41
 42 43 45 46 47 48 49 50 51 54 55 56 61 64 65 67 68 70 75 76 78 79 80 83
 84 85 87 88 92 94 95]


In [11]:
# Diferencia del array1 y el array2
array3 = np.setdiff1d(array1,array2)
array3

array([ 7, 10, 11, 13, 14, 18, 23, 24, 26, 44, 57, 58, 60, 62, 66, 69, 71,
       72, 73, 77, 82, 90, 93, 97, 98, 99])

In [12]:
# Diferencia del array2 y el array1
array4 = np.setdiff1d(array2,array1)
array4

array([ 1,  9, 17, 20, 27, 29, 30, 32, 34, 35, 36, 39, 41, 42, 45, 47, 48,
       50, 51, 64, 65, 68, 70, 79, 80, 88, 92, 94])

In [13]:
# Union de los 2
array5 =np.union1d(array1,array2)
array5

array([ 1,  3,  6,  7,  8,  9, 10, 11, 13, 14, 15, 16, 17, 18, 20, 21, 22,
       23, 24, 25, 26, 27, 29, 30, 31, 32, 33, 34, 35, 36, 37, 39, 41, 42,
       43, 44, 45, 46, 47, 48, 49, 50, 51, 54, 55, 56, 57, 58, 60, 61, 62,
       64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 75, 76, 77, 78, 79, 80, 82,
       83, 84, 85, 87, 88, 90, 92, 93, 94, 95, 97, 98, 99])

In [14]:
# Valores únicos del 1
len(array1)

53

In [15]:
# Valores únicos del 2
len(array2)

55

In [16]:
#Diferentes, los que están en el 1 pero no en el 2
len(array3)

26

In [17]:
#Diferentes, los que están en el 2 pero no en el 1
len(array4)

28

In [18]:
# Union de ambos
len(array5)

81

In [19]:
# La len o size del array1 más lo que está en el array2 pero no en el array1 es igual a la len o size de la unión de ambos
len(array1) + len(array4) == len(array5)

True

In [20]:
# La len o size del array2 más lo que está en el array1 pero no en el array2 es igual a la len o size de la unión de ambos
len(array2) + len(array3) == len(array5)

True

Con los métodos de union y diferencia entre arrays como solo devuelve valores únicos es como utilizar operaciones matemáticas:
- setdiff1d: resta los arrays teniendo en cuenta el orden de los factores
- union1d: suma los arrays

Lo podemos ver en que la longitud del union se corresponde con la suma de la len del array1 y de la len de la diferencia del array2 con el array1, y con las len del array2 y de la diferencia de la len del 1 con el 2.
