1- Cread un array de dos dimensiones de 5 filas y 3 columnas. Sobre el array creado anteriormente, extraed:
- El valor de la primera fila y la segunda columna.
- Los valores de la segunda fila y las dos primeras columnas.
- Extraed las filas pares (incluyendo la 0) y todas las columnas.
- Extraed los valores que sean mayores que 0.5.
- Extraed los valores menores que 0.2 o mayores que 0.5

In [1]:
import numpy as np

In [2]:
array1 = np.random.rand(5,3)
array1

array([[0.23844571, 0.06981108, 0.63521506],
       [0.46916144, 0.29676282, 0.18476016],
       [0.18807122, 0.58261785, 0.74889921],
       [0.40289236, 0.16589811, 0.22853072],
       [0.7838223 , 0.66686213, 0.86394446]])

In [3]:
#Primera fila y segunda columna
array1[1,2]

0.1847601644217255

In [4]:
#Valores de la segunda fila y las dos primeras columnas
array1[2,0:2]

array([0.18807122, 0.58261785])

In [5]:
#Filas pares incluyendo 0 y todas las columnas
array1[::2,:]

array([[0.23844571, 0.06981108, 0.63521506],
       [0.18807122, 0.58261785, 0.74889921],
       [0.7838223 , 0.66686213, 0.86394446]])

In [6]:
#Valores mayores de 0,5
array1[array1>0.5]

array([0.63521506, 0.58261785, 0.74889921, 0.7838223 , 0.66686213,
       0.86394446])

In [7]:
#Valores menores que 0,2 y mayores de 0,5
array1[(array1<0.2)|(array1>0.5)]

array([0.06981108, 0.63521506, 0.18476016, 0.18807122, 0.58261785,
       0.74889921, 0.16589811, 0.7838223 , 0.66686213, 0.86394446])

2. Cread dos array de tres dimensiones:
- El primero de 2 matrices, 5 filas y 3 columnas.
- El segundo de 3 matrices, 2 filas y 5 columnas
- Haced un análisis exploratorio de los array creados. Recordad que en el ejercicio de ayer nos creamos una función para esto.
- Sumad los dos arrays. ¿Podéis? ¿Por qué?
- Para cambiar la forma de un array y poder hacer operaciones entre arrays que tienen distintas formas hemos aprendido dos métodos:
.reshape()
.transpose()
Utiliza estas dos funciones para cambiar la forma de los array y hacer operaciones entre ellos.

In [8]:
array2 = np.random.rand(2,5,3)
array2

array([[[0.9824937 , 0.4953007 , 0.7000378 ],
        [0.61852029, 0.93312706, 0.34382488],
        [0.61561196, 0.68997893, 0.64310807],
        [0.80301769, 0.7077403 , 0.6811093 ],
        [0.72212378, 0.59805614, 0.8203058 ]],

       [[0.81260771, 0.86067712, 0.06799255],
        [0.40836545, 0.67137541, 0.35367683],
        [0.99040062, 0.2913153 , 0.34030878],
        [0.04630584, 0.72360106, 0.98843353],
        [0.95033697, 0.18391872, 0.38517101]]])

In [9]:
array3 = np.random.rand(3,2,5)
array3

array([[[0.31155242, 0.86864061, 0.1938057 , 0.60083833, 0.70726656],
        [0.21781435, 0.20432543, 0.80222647, 0.7544136 , 0.09682637]],

       [[0.60745246, 0.51067955, 0.98714957, 0.56704551, 0.41352115],
        [0.86210934, 0.09329534, 0.82783187, 0.85027256, 0.23810859]],

       [[0.57949819, 0.56755442, 0.68773187, 0.26409788, 0.54887708],
        [0.79126772, 0.73671152, 0.56748284, 0.63317314, 0.11387893]]])

In [10]:
#Usamos la función definida en el pair anterior
def propiedades(array): 
    print(f'La forma es {array.shape}')
    print(f'El tamaño es {array.size}')
    print(f'La dimensión es {array.ndim}')
    print(f'El tipo es {array.dtype}')

In [11]:
propiedades(array2)

La forma es (2, 5, 3)
El tamaño es 30
La dimensión es 3
El tipo es float64


In [12]:
propiedades(array3)

La forma es (3, 2, 5)
El tamaño es 30
La dimensión es 3
El tipo es float64


In [13]:
array4 = np.add(array2,array3)
#No se pueden sumar ambos arrays porque no tienen la misma forma

ValueError: operands could not be broadcast together with shapes (2,5,3) (3,2,5) 

In [14]:
#Cambiamos la forma de array3 con reshape para hacerla igual que array2
array3_reshaped = np.reshape(array3, (2,5,3))
array3_reshaped

array([[[0.31155242, 0.86864061, 0.1938057 ],
        [0.60083833, 0.70726656, 0.21781435],
        [0.20432543, 0.80222647, 0.7544136 ],
        [0.09682637, 0.60745246, 0.51067955],
        [0.98714957, 0.56704551, 0.41352115]],

       [[0.86210934, 0.09329534, 0.82783187],
        [0.85027256, 0.23810859, 0.57949819],
        [0.56755442, 0.68773187, 0.26409788],
        [0.54887708, 0.79126772, 0.73671152],
        [0.56748284, 0.63317314, 0.11387893]]])

In [15]:
#Sumamos
array4 = np.add(array2,array3_reshaped)
array4

array([[[1.29404612, 1.36394131, 0.89384351],
        [1.21935863, 1.64039362, 0.56163923],
        [0.81993739, 1.49220539, 1.39752167],
        [0.89984406, 1.31519276, 1.19178885],
        [1.70927335, 1.16510165, 1.23382695]],

       [[1.67471705, 0.95397246, 0.89582443],
        [1.25863801, 0.909484  , 0.93317502],
        [1.55795503, 0.97904716, 0.60440665],
        [0.59518291, 1.51486878, 1.72514504],
        [1.51781981, 0.81709186, 0.49904994]]])

In [16]:
#Cambiamos la forma de array3 con transposed la posición 1 a la 0, la 2 a la 1 y la 0 a la 2.
array3_transposed = np.transpose(array3, (1,2,0))
array3_transposed

array([[[0.31155242, 0.60745246, 0.57949819],
        [0.86864061, 0.51067955, 0.56755442],
        [0.1938057 , 0.98714957, 0.68773187],
        [0.60083833, 0.56704551, 0.26409788],
        [0.70726656, 0.41352115, 0.54887708]],

       [[0.21781435, 0.86210934, 0.79126772],
        [0.20432543, 0.09329534, 0.73671152],
        [0.80222647, 0.82783187, 0.56748284],
        [0.7544136 , 0.85027256, 0.63317314],
        [0.09682637, 0.23810859, 0.11387893]]])

In [17]:
#Sumamos
array5 = np.add(array2,array3_transposed)
array5

array([[[1.29404612, 1.10275317, 1.279536  ],
        [1.4871609 , 1.44380661, 0.9113793 ],
        [0.80941767, 1.67712849, 1.33083994],
        [1.40385603, 1.27478581, 0.94520718],
        [1.42939034, 1.01157729, 1.36918288]],

       [[1.03042206, 1.72278646, 0.85926028],
        [0.61269088, 0.76467075, 1.09038834],
        [1.79262709, 1.11914717, 0.90779161],
        [0.80071944, 1.57387362, 1.62160667],
        [1.04716334, 0.42202731, 0.49904994]]])